apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260621-135120-s512sj1b9w39-service
spec:
  selector:
    app: enterprise-system-20260621-135120-s512sj1b9w39
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
